Tc 99
CS3733-D22-Team-C/Prototype-C pull request #14
Opened 2022-03-29 18:33 UTC by njpires20

- Added Location Select Controller and FXML
- Added Location Select constant to App

2022-03-30 17:10 UTC, bdvuong commented
Looks good to me, can we instead merge this branch into TC-85 which is the toolbar stuff then I can merge that into main?

2022-03-30 17:10 UTC, bdvuong approved these changes

2022-03-30 17:52 UTC, MacCode7110 approved these changes

2022-03-30 23:21 UTC, JohnMuirhead000 requested changes
boxes dont have full words in them D:

2022-03-31 01:22 UTC, mmueting approved these changes
Looks good

2022-03-31 01:26 UTC, merged